BEGIN
BEGIN TRANSACTION trans1
BEGIN TRY

	CREATE TABLE Bank (
	  ID int primary key identity,
	  BankName varchar(255),
	  CardType varchar(255),
	  Number varchar(255)
	);

	INSERT INTO Bank (BankName,CardType,Number) VALUES ('PT. BANK PERMATA TBK ','VISA ','489385');
	INSERT INTO Bank (BankName,CardType,Number) VALUES ('PT. BANK BUKOPIN ','VISA ','489781');
	INSERT INTO Bank (BankName,CardType,Number) VALUES ('PT BANK MANDIRI (PERSERO) TBK ','VISA ','490283');
	INSERT INTO Bank (BankName,CardType,Number) VALUES ('PT BANK DANAMON INDONESIA TBK ','VISA ','490295');
	INSERT INTO Bank (BankName,CardType,Number) VALUES ('PT BANK DANAMON INDONESIA TBK ','VISA ','490296');
	INSERT INTO Bank (BankName,CardType,Number) VALUES ('BANK BALI ','VISA ','490702');
	INSERT INTO Bank (BankName,CardType,Number) VALUES ('STANDARD CHARTERED BANK ','VISA ','493497');
	INSERT INTO Bank (BankName,CardType,Number) VALUES ('BANK INTERNASIONAL INDONESIA ','VISA ','493828');
	INSERT INTO Bank (BankName,CardType,Number) VALUES ('BANK INTERNASIONAL INDONESIA ','VISA ','493829');
	INSERT INTO Bank (BankName,CardType,Number) VALUES ('PT. BANK PERMATA TBK ','VISA ','498853');
	INSERT INTO Bank (BankName,CardType,Number) VALUES ('PT. ANZ PANIN BANK ','MASTERCARD ','510217');
	INSERT INTO Bank (BankName,CardType,Number) VALUES ('PT. ANZ PANIN BANK ','MASTERCARD ','510249');
	INSERT INTO Bank (BankName,CardType,Number) VALUES ('STANDARD CHARTERED BANK ','MASTERCARD ','510457');
	INSERT INTO Bank (BankName,CardType,Number) VALUES ('PT. BANK RAKYAT INDONESIA (PERSERO) ','MASTERCARD ','510458');

--ROLLBACK TRANSACTION trans1
COMMIT TRANSACTION trans1

END TRY
BEGIN CATCH

SELECT ERROR_MESSAGE()
ROLLBACK TRANSACTION trans1
END CATCH

END
